name: AdditionalBlocks
version: '${project.version}'
main: com.mcrebels.additionalblocks.additionalblocks.AdditionalBlocks
api-version: 1.18
authors: [ xSolum ]
description: add more blocks
commands:
  custominv:
    description: opens block inventory
    permission: additionalblocks.admin
  extrablocks:
    description: ^^
    permission: additionalblocks.admin
